imports:
    - { resource: parameters.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/{Command,Service}'

    Symfony\Component\Console\Application:
        public: true

    App\Service\ExactService:
        class: App\Service\ExactService
        arguments: ['%username%', '%password%', '%otp_seed%']